# R 言語の入門

このシートは自習学習で本講義で必要なR言語の機能を一通り学びます。



# 1 変数と代入

x, y, z のような文字は変数をあらわします。

x <- 3 は変数にxという変数に3という数値を記憶させることを意味します。


In [ ]:
x <- 3
print(x)

今使っているのは Jupyter Notebook というプログラミング環境で、上にあるような枠をセルといいます。セルにはプログラムコードを記入し、左側の実行ボタンで実行すると、セルの下に出力が表示されます。

Jupyter Notebook では、セルを実行した後も変数の値は残っています。ですから以下の結果も3になります。

In [ ]:
print(x)

そしてyはまだ定義されていないから以下はエラーになります。

In [ ]:
print(y)

同じ変数に異なる値を代入することも可能です。再度代入を行うと値は上書きされて、古い値は捨てられます。

In [ ]:
y <- x
x <- 39281
print(x)
print(y)

上の例では、x に新しい値が代入される前に古い値をyに代入してあったから、y の値は3になっていました。

### プログラミング初心者の方への注意
このようにプログラミングでは命令の順序が大きな意味を持ちますので、代入が順序を追っておこなわれることに注意してください。

変数名は、英字で始まること、そして英字、「_」下線、数字であらわします。
例を示します。

In [ ]:
x <- 123
totemo_nagai_namaeno_hensu <- x
p456 <- totemo_nagai_namaeno_hensu
print(p456)


でも以下はエラーになります。

~~~
hensu mei <- 3
123x <- 5
room-3 <- 7

~~~

In [ ]:
room-3 <- 7

ERROR: ignored

日本語はつかえるようですが、多分あまり使わない方がよいかと思います。
いつも使えるとは限らない。
海外の人に不親切。

## 練習問題

ただしい変数、間違った変数を2つずつ考えてください。



x <- 123
y <- 456
ここに, x と y を入れ替えるプログラムを書いてください
print(x)
print(y)

# 2 printとpaste

すでにprintを使いましたが、以下のように paste を使うと文字列と変数の出力を組み合わせて見やすく表示することができます。

In [ ]:
paste("x=", x)
paste("y=", y)
paste("p456=",p456)

# 3 演算子

加減乗除などの記号は下記の通りです

|  種別  |  記号  |
|---:---|--:--|
| 加算、減算|   + , -|
| 乗算、除算|   * , /|
| 累乗 | ** |



In [ ]:
paste("123000+567 =", 123000+567)
paste("3*4 =", 3*4)
paste("4/3 =", 4/3)
paste("10**3=", 10**3)


# 4 ベクトル

ベクトルを c(2,3,4,5,6) のようにあらわせます。
このベクトルですが、R 言語では数学のベクトルと同じ意味だけでなく、様々な使い方をします。似ていますが、ちょっと違うと思ってください。

ベクトルは一旦変数に代入されると、複数の数値の列になります。
c(1,2)のように書きますが、c はベクトルだよという記号として使っているだけでそれ以外に意味はありません。
したがって、print すると数値の列だけが表示されます。

ベクトルへの計算は、すべての要素に対する計算結果の列になります。

In [ ]:
x <- c(2,3,4,5,6)
print(x)
print(x + 1)
print(x* 10)

vector を使って False からなるベクトルを作ることもできます。False はまだ数値が入っていないことを表します。

In [ ]:
x <- vector(length=5)
print(x)

[1] FALSE FALSE FALSE FALSE FALSE
     [,1] [,2] [,3]
[1,]    2    3    5
[2,]    1    4    7


数値を一つ一つ与えるかわりに、数列を作ることもできます。

以下は、数列の例です。

In [ ]:
print(1:3)
print(10:7)



rep を使うと同じ数のくりかえし、seq を使うと一定間隔の数列を作れます。

In [ ]:
print(rep(1,3))
print(rep(0,5))
print(seq(2,12,3))
print(seq(10,-10,-3))

## 練習問題
以下のような数列を作ってください。

~~~
1 6 11 16 21 26 31
999 998 997
-55 -57 -59 -61
~~~


# 5 数値表現、文字列、paste


R言語では小数は普通に小数点を使って表します。
指数表示は  123e4 のように e(数字) と書き表します。
文字列はシングルクオートかダブルクオートであらわします。

In [ ]:
print(123.45)
print(123e4)
print(1e-2)
print(1e-44)
print('The quick brown fox...')


## 練習問題
結果が 3 になるようにしてください

In [ ]:
x <- 3e10
y <- ここを変更
print(x / y)

#6 配列
配列はarray で作成できます。dimの後はベクトルで、これは次元サイズの列になります。まず例をみてみましょう。

In [ ]:
x <- array(0, dim=c(3))
print(x)

dim=c(3) なので長さ3の次元が1つの配列ができます。

dim=c(2,2)なら2x2、dim=c(4,5,2)なら 4 x 5 x 2 の配列ができます。

In [ ]:
print('array(0, dim=c(2,2))')
print(array(0, dim=c(2,2)))
print('array(0, dim=c(3,4,2))')
print(array(0, dim=c(3,4,2)))


行列は matrix で作ることができます。
行列のサイズや行列内の数値は、ベクトルで指定することができます。

In [ ]:
A <- matrix(c(c(1, 2), c(11,12)), c(2,2))
print(A)
A <- matrix(c(c(1, 2, 3), c(11,12,13)), c(3,2))
print(A)

ところで、array や matrix で数値を与えるベクトルはひとつにまとめてもかまいません。すべてのベクトルの値をつなげて使っていきます。

In [ ]:
A <- matrix(c(c(1), c(11,12,13),c(21,22)), c(3,2))
print(A)

In [ ]:
x <- array(c(c(1), c(11,12,13),c(21,22,23),c(31)),c(2,2,2))
print(x)

## 練習問題
以下のmatrix を作ってください

~~~

     [,1] [,2] [,3] [,4] [,5]
[1,]    1    3    5    7    9
[2,]    2    4    6    8   10

~~~

In [ ]:
x <- matrix(ここを埋める)
print(x)

     [,1] [,2] [,3] [,4] [,5]
[1,]    1    3    5    7    9
[2,]    2    4    6    8   10
